### ISSUE TITLE
Connection Throttled

### ISSUE THREAD

**Issue by ygtdmn** [WaterfallMC/Waterfall-Old#61] opened 2016-04-26 21:06 UTC
In build #196 nobody can join the server. In console it says connection was throttled and players getting error all time. It says connection is throttled.

**Comment by Janmm14** [comment] 2016-04-26 21:15
Do not use the last 5 builds (If I counted correctly).

Issue is already identified by me.

One can see here what is done wrong in code: https://github.com/WaterfallMC/Waterfall/commit/06d647ea8c14a0e62ac320732423f65d0aa9ce42#commitcomment-17252124

**Comment by Techcable** [comment] 2016-04-27 00:08
Duplicate of #26

**Closed as completed by Techcable** 2016-04-27 00:08 UTC
Labels: duplicate
